### ISSUE TITLE
feature request, item weight

### ISSUE THREAD

**Issue by nutpantz** [nbossard/packlist#13]
I've been looking for a new good packing list app
So I will be watching the development of this app.
Personally I need to have weights added to my list items
With a running total of weight for each list.
Would be nice if there was a luggage group option with weight of all luggage
(Ie a running total of bag, suitcase, carry on separately and together, but I've never seen this before)

These are just ideas when the time comes
And extra great this open source.
Thanks for contributing to the community.

**Comment by nbossard** [comment]
Hello Nupantz, 
Thanks for the suggestion, it is a good idea.
I need to add a possibility to add detail on item like quantity, category, value...
This needs a few new screen and model update, I will keep you informed.
Best regards, Nicolas

**Comment by nbossard** [comment]
Hello Nupantz, 
I have added most of what you suggested in release 0.8. (available since today 9th of april).
Please have a look.
Best regards, Nicolas

**Comment by nutpantz** [comment]
Looks great to start. Two  thoughts only
it would be nice to see total weight of packed items not total weight of all list items
(Some things in the list don't always get packed)
Total packed item weight in the trips screen.
I don't pack for different trips as I have a list for the bag based on season and activities
Ie list of swimming gear for a bag, for when I might so swimming
list of winter clothes to take. In winter. Etc.
So the trips screen is really a list of bags or packs for me.

Very nice work,

**Comment by nbossard** [comment]
Hello Nupantz, 
I am happy it (partly) suits your need. Please signal me any bug you might encounter.

Concerning the packed item weight I have created issue #22 , please subscribe to it, il will be easily and consequently quickly done :-)

Concerning your activities lists, I think you have the right approach, I am planning to allow user to pre create thematic lists corresponding to his usual activities and then when creating a new trip, user will be asked if he plans to do each activity. New trip will then be pre-filled with an item list corresponding to activities he agreed.
See #8 for this incoming feature.
