### ISSUE TITLE
Using rotation enough times will cause overlay problems

### ISSUE THREAD

**Issue by snelltheta** [nbossard/packlist#17]
If I rotate a few times and open up event details or edit event, there is no new canvas, so everything apostate on top of each other.

**Comment by snelltheta** [comment]
Update: the back button is able to remove the offending overlaying windows.

**Comment by nbossard** [comment]
investigating...

**Comment by nbossard** [comment]
This was due to activity being restarted when rotated. Side-fixed by fixing ISS#15
