### ISSUE TITLE
Crash when no start date

### ISSUE THREAD

**Issue by nbossard** [nbossard/packlist#18]
crash on trip list when a trip is created without start date

**Comment by code-surfer** [comment]
The app crashes when I enter a trip name only and hit `LET'S GO...`.
When I start the app again, the trip is there, so it crashed after saving it.
This is with version 0.8.

**Comment by nbossard** [comment]
Hello code surfer,
Of course I tested creating a trip without date... And it worked fine :-)
That is the magic of Android.
I don't see any crash in developer play console,  that means you have not
uploaded crash report or it does not work with releases coming from f-droid.
Can you please create an issue on Github with info like Android version.
I will create another feature enhancement in Github for adding a crash
report tool, which needs to be discussed.
Best regards, Nicolas

**Comment by nbossard** [comment]
Created issue #25 for better understanding of your bug.
