### ISSUE TITLE
date display is garbled

### ISSUE THREAD

**Issue by code-surfer** [nbossard/packlist#19]
packlist displays the lists with their date range. Unfortunately, the displayed dates are garbled, the order of year, month, day is not what I configured in the Android settings.

**Comment by nbossard** [comment]
Dates are formatted using system conventions : see Trip.java line 151

```
        res = DateFormat.getDateInstance(DateFormat.SHORT).format(mStartDate.getTime());
```

This results in format change according to system language-locale in settings.

For example if I put my device in... 26th of march 2016 is displayed 
french (france) : 26/03/16
french (canadian ) : 16-03-26 
english (united states) : 3/26/16

**Comment by code-surfer** [comment]
In Settings->Language & input, I've set "Language" to "English". There's only one English, no regional choices. In Date & time, for "Choose date format" I chose 2016/12/31 instead of the first option "Regional (12/31/2016)".

F-droid for example displays the packlist 0.6 release as "Added on 2016/03/11", conforming to my chosen format.
packlist displays a trip starting today as 3/20/16, seemingly conforming to the regional format I have _not_ chosen.
Interestingly, some pre-installed apps like Phone (e.g. 11/25/2015) also seem to get it wrong.
Osmand~ gets it right, e.g. 2016/01/17.

Unfortunately, I hardly know anything about Android programming, but to me this feels like there are two alternate ways of doing it, and one does it better than the other. ;-)
Or there's yet another place in the system settings where to configure the date format?
It's an Android 4.2.2, in case this explains this mess.

**Comment by nbossard** [comment]
Thanks for your study, 
Will try fixing it using suggestion in : 
http://stackoverflow.com/questions/6981505/how-to-get-user-selected-date-format-in-android

**Comment by nbossard** [comment]
Fixed in develop

**Comment by nbossard** [comment]
Fixed in release 0.7.1

**Comment by nbossard** [comment]
Hello code-surfer, could you please install 0.7.1, available on f-droid and playstore and tell me if fix is working fine, then close or update this bug.
Best regards, Nicolas

**Comment by code-surfer** [comment]
Testing with the lastest on F-Droid, 0.7.1, I can confirm that the date now gets formatted according to the chosen date format in the Android settings. (I also set changed them back and forth.) Well done!
