### ISSUE TITLE
packlist display jumps to top upon every (un)pack of an item

### ISSUE THREAD

**Issue by code-surfer** [nbossard/packlist#21]
Whenever I click on an item to mark it as (un)packed, the item list gets scrolled to its top. My list is some four screens long, which means I click, have to scroll down a few screens to get back to where I was, click the next item, scroll down again a few screens, click...
The items are also displayed with a pretty low height, so from time to time I click the wrong one, so I have to do the scrolling down procedure three times for one item.

**Comment by nbossard** [comment]
Looks very very disturbing, thanks for signaling, 
I will fix it ASAP (autoscrolling, increase row size).

**Comment by nbossard** [comment]
Fixed (on branch develop)

**Comment by nbossard** [comment]
Fixed in release 0.7.1

**Comment by nbossard** [comment]
Hello code-surfer, could you please install 0.7.1, available on f-droid and playstore and tell me if fix is working fine, then close or update this bug.
Best regards, Nicolas

**Comment by code-surfer** [comment]
With the latest from F-Droid, 0.7.1, I can confirm that the list does not jump any more and that the higher rows are easier to hit now.
