### ISSUE TITLE
how about check boxes instead of text?

### ISSUE THREAD

**Issue by code-surfer** [nbossard/packlist#23]
I find it a little hard to spot unpacked items in the list, because it's all text. Have you considered using check boxes instead? Perhaps full GUI checkbox widgets with their overhead(?) aren't even necessary, if the Unicode support covers enough symbols? In http://www.unicode.org/charts/PDF/U2600.pdf I found U+2610 BALLOT BOX and U+2611 BALLOT BOX WITH CHECK. Perhaps you'd like to give it a try? :-)

(Side note: according to English (and German) typographic rules, there's no space before punctuation, i.e. it should be "PACKED:", not "PACKED :".)

**Comment by nbossard** [comment]
You are right, checkboxes would be better as users are more used to this design, I had issues with onclick on check boxes, so I made this quick win. I will change this in next release.
Thanks for the typo, I fix it straight now.

**Comment by nbossard** [comment]
Done, will be in release 0.8.1
