### ISSUE TITLE
Sorting the list of items

### ISSUE THREAD

**Issue by DonChunior** [nbossard/packlist#24]
Please add the functionality to sort the list of items of a trip.
The sorting function should put packed items to the end of the list!

**Comment by nbossard** [comment]
Hello DonChunior,
There is a sorting on trips based on trip start date but not on items.
I am not sure that reordering of item lists based on packing state would not be a little confusing as items would be changing position in the list all the time. I can give it a try with a dedicated release so you can play with this feature. I will keep you informed.

**Comment by DonChunior** [comment]
Hi nbossard,
if it gets sorted automatically, it would be confusing.
But if I'd be able to activate this functionality explicitely by a button or something like that, it would be a nice feature.
Thanks so far!

**Comment by nbossard** [comment]
Hello DonChunior,
Ok I will leave it as is and implement an optional sorting as you suggest (packed/unpacked) throught an icon in actionbar.
Will probably do it in 0.8.1

**Comment by DonChunior** [comment]
Thanks, nbossard!

**Comment by nbossard** [comment]
Added, will be in next release

**Comment by nbossard** [comment]
Added in release 0.8.1. Consequently closing issue.
