### ISSUE TITLE
feature enhancement : crash report tool

### ISSUE THREAD

**Issue by nbossard** [nbossard/packlist#25]
As user number grows we definitely need a crash report tool for better understanding non-trivial problems like this encountered by @codesurfer in issue #18.
This tool must at least send:
- stack trace
  -app logs
- info about device : version, device manufacturer and model

I have been using fabrics (aka crashlytics) in other projects, it does the job but it is not very "open-source spirit" as it sends unknown data to private company (Twitter).
I would prefer a more simpler tool like Github project [ACRA](https://github.com/ACRA/acra) which generates report that can be sent by email [see](https://github.com/ACRA/acra/wiki/Report-Destinations#sending-reports-by-email), which prevents adding INTERNET permission. But any other suggestion is welcome...

**Comment by nbossard** [comment]
Added to develop, will be in next release

**Comment by nutpantz** [comment]
A simple email send with the required info is the way I like to see it done
That way if I see what's wrong I can point it out
And if I have no idea I can see what info is sent.

**Comment by nbossard** [comment]
Well, so you will like the just implemented solution using ACRA configured in email report mode. :-)
If you encounter a crash of course...

**Comment by nbossard** [comment]
Available in release 0.8.1, consequently closing issue.
