### ISSUE TITLE
export to readable format

### ISSUE THREAD

**Issue by nutpantz** [nbossard/packlist#27]
A way to export a list to a readable format would be nice
Something simple like csv or a compressed text file
Both export and import items

Maybe a printable text, html or epub export.
Just for the love of God stay away from pdf.

**Comment by nbossard** [comment]
Hello Nupantz
you are right,  there needs an export functionality.
I was thinking of a share button in trip action bar that would export as human readable formatted text, one item per line.
A format that would be compatible with the existing mass import functionality.

**Comment by nbossard** [comment]
Note : May be use new ShareCompat
http://developer.android.com/reference/android/support/v4/app/ShareCompat.html

**Comment by nbossard** [comment]
Done in develop  branch, will be in next release

**Comment by nbossard** [comment]
Delivered in release 0.9, closing issue.
