### ISSUE TITLE
copy share items between trips, lists.

### ISSUE THREAD

**Issue by nutpantz** [nbossard/packlist#28]
Many times I have to make a new list similar but not exact to one I use all the time
It would be nice to have simply pick all the things in a list (maybe as packed) then have an option
To send all those things to another trip, or list in a trip as a copy or move function..

I would find this very very useful.

**Comment by nbossard** [comment]
Hello @nutpantz
Did you notice the existing trip clone functionality available if you make a long click on a trip in the main screen.
This might cover part of your need.

I will work on the list functionnality #8 that will cover the rest hopefully :-)

**Comment by nbossard** [comment]
Closed as discussion is no longer active.
