### ISSUE TITLE
Group items by category on a single card

### ISSUE THREAD

**Issue by nbossard** [nbossard/packlist#49]
Suggestion by mister X : 
Creating a category card for every item makes the list very lengthy, especially when you have a lot of items to pack. Therefore, I suggest that all items belonging to the same category should be grouped under a single card (see pic). This card can be collapsed/expanded with a single tap if more than one item is listed in it. Do provide an indicator for cards that can be expanded. Also, all the items inside a card should have their own check box. And only after every item in the card has been checked, will the card itself also get checked automatically. Not the other way around. This way the user will not be able to make the mistake of checking the card — thereby automatically checking all the items in it — even though he/she forgot to pack certain items listed in that card.

**Comment by ghost** [comment]
@nbossard Need checklist within categories. (Checklist in pic from Omni Notes FOSS).

![packlist](https://user-images.githubusercontent.com/26545454/29221812-cc6ccca6-7ec8-11e7-8160-9e306b37cf30.png)

**Comment by nbossard** [comment]
duplicate with issue #57, closing this one
