### ISSUE TITLE
New logo proposal: Packlist

### ISSUE THREAD

**Issue by baranpirincal** [nbossard/packlist#74]
Hello, I examined your project and I saw that your existing logo looks amateur and generic. If you interested I can contribute to your project with making logo design.  My purpose is make my portfolio better with supporting open-source projects. I can show my portfolio if you want to. I am waiting your feedbacks, have a nice day!

Best Regards
Baran Pirinçal
Graphic Designer

**Comment by nbossard** [comment]
Hello Baran, 
Thanks for your proposal. Currently jaldesign93 is trying to improve the application logo, see merge request : https://github.com/nbossard/packlist/pull/73
But this is progressing slowly, may be you can support him or provide additinal graphics for the app.
For sure your name would appear in about page of the application and you could use it as a reference.
Best regards, Nicolas.

**Comment by baranpirincal** [comment]
@nbossard 

Hey again, 

I made a adaptive logo design as you wish. I want to take feedback from you. After that I will do some arrangements.  :) (Maybe we can lines thicker)

My idea:  Ticket & Bag & List 

(I want to show ticket with using bar-code and dot lines)

![packlist](https://user-images.githubusercontent.com/37786733/41194723-f5a9f168-6c28-11e8-8251-0c5708ee3d3d.jpg)




Best Regards
Baran Pirinçal

**Comment by baranpirincal** [comment]
![22](https://user-images.githubusercontent.com/37786733/41197050-b3d700d8-6c59-11e8-8251-02dea75c9722.jpg)
