### ISSUE TITLE
move item automatically down when ticked

### ISSUE THREAD

**Issue by natrius** [nbossard/packlist#75]
Using 0.13 via F-Droid on Android 8.1 with LineageOS

As said, i like to prefer to sort it alphabetical but it would be nice to just see whats still open. 
So an additional option would be nice for that in the settings.

**Comment by nbossard** [comment]
Thanks for the suggestion, I will study if feasible without changing everything, best regards, Nicolas.

**Comment by nbossard** [comment]
OK, I am modifying the "unpacked first" ordering to make it sort first by packed / unpacked then by category then by alphabetical order.

**Comment by nbossard** [comment]
Ok done, will be in next release, probably next week, Nicolas
